mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^start/', include('start.urls')),
    url(r'^sampling_event/', include('sampling_event.urls')),
    url(r'^chaining/', include('smart_selects.urls')),

]

polls/urls.py
from django.conf.urls import  url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    ]

sampling_event/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'sampling_event'

urlpatterns = [

    url(r'^chaining/', include('smart_selects.urls')),

    url(r'^$', views.index, name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),


    #sampling_event/001
    url(r'^(?P<sampleEvent_id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^sampleEvent/add/$', views.sampleEventCreate.as_view(), name='sampleEvent-add'),

    url(r'^sampleEvent/(?P<pk>[0-9]+)/$', views.sampleEventUpdate.as_view(), name='sampleEvent-update'),

    url(r'^sampleEvent/(?P<pk>[0-9]+)/delete/$', views.sampleEventDelete.as_view(), name='sampleEvent-delete'),





    # sampling_event/sample/1
    url(r'^sample/(?P<pk>[0-9]+)/$', views.sampleIndex, name='sample-index'),



    url(r'^sample/add/$', views.sampleCreate.as_view(), name='sample-add'),

    url(r'^sample/(?P<pk>[0-9]+)/$', views.sampleUpdate.as_view(), name='sample-update'),

    url(r'^sample/(?P<pk>[0-9]+)/delete/$', views.sampleDelete.as_view(), name='sample-delete'),

]

sampling_event/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from smart_selects.db_fields import ChainedForeignKey

from django.core.urlresolvers import reverse

from django.contrib.auth.models import AbstractBaseUser


class Mission(models.Model):
    missionName = models.CharField(max_length=50)

    def __str__(self):
        return str(self.missionName)


class Sampler(models.Model):
    mission = models.ForeignKey(Mission, default=1)
    firstName = models.CharField(max_length=20)
    lastName = models.CharField(max_length=20)

    def __str__(self):
        return str(self.firstName) + ' ' + str(self.lastName)


class Site(models.Model):
    #mission = models.ForeignKey(Mission, default=1)
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)


class SampleType(models.Model):
    method = models.CharField(max_length=10)
    efficiency = models.IntegerField()
    area = models.IntegerField()
    volume = models.DecimalField(max_digits=10, decimal_places=4 )
    platesCreated = models.IntegerField()

    def __str__(self):
        return str(self.method)


class Facility(models.Model):
    Site = models.ForeignKey(Site)
    name = models.CharField(max_length=100)

    def __str__(self):
         return str(self.name)


class Environment(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)


class Spacecraft(models.Model):
    mission = models.ForeignKey(Mission, default=1)
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)


class Zone(models.Model):
    mission = models.ForeignKey(Mission, default=1)
    name = models.CharField(max_length = 20)

    def __str__(self):
        return str(self.name)


class PooledID(models.Model):
    Zone = models.ForeignKey(Zone, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)


class Coge(models.Model):
    firstName = models.CharField(max_length=20)
    lastName = models.CharField(max_length=20)

    def __str__(self):
        return str(self.firstName) + ' ' + str(self.lastName)

class sampleEvent(models.Model):

    mission = models.ForeignKey(Mission, default=1)
    date = models.DateField(default=datetime.date.today)
    assayName = models.CharField(max_length = 100)

    coge = models.CharField(max_length = 100) #eo
    samplers = models.ManyToManyField(Sampler)
    Site = models.ForeignKey(Site)
    facility = ChainedForeignKey(Facility, chained_field="Site", chained_model_field="Site", null=True, blank=True, default=None)
    #facility = models.CharField(max_length = 100) #eo
    environment = models.ForeignKey(Environment)



    def get_absolute_url(self):
    #    return "/sampling_event/{{self.id}}/"
        return reverse('sampling_event:detail', kwargs={'sampleEvent_id': self.id})

    def __str__(self):
        return self.assayName + '-' + str(self.id)
    #INCLUE PICTURES


class sample(models.Model):
    samplingEvent = models.ForeignKey(sampleEvent, on_delete=models.CASCADE)
    sampleType = models.ForeignKey(SampleType)
    accountable = models.BooleanField(default=True)

    Zone = models.ForeignKey(Zone, null=True, blank=True, default=None)
    PooledID = ChainedForeignKey(PooledID, chained_field="Zone", chained_model_field="Zone", null=True, blank=True, default=None)
    serialNumber = models.CharField(max_length=100, null=True, blank=True, default=None)
    description = models.CharField(max_length = 400, null=True, blank=True, default=None)

    #plates = models.IntegerField() - sampleType.platescreated

    #needs to be changed
    def get_absolute_url(self):
    #    return "/sampling_event/sample/{{self.id}}/"
        return reverse('sampling_event:sample-index', kwargs={'sample_id': self.id})

    def __str__(self):
        return str(self.sampleType) + '-' + str(self.id)


class plate(models.Model):
    sample = models.ForeignKey(sample, on_delete=models.CASCADE)

    #barcode = spacecraft - sampling event - sample - plate type - plate number
    #barcode = str(sample.samplingEvent) + str(sample.primary_key)

    sporeCount24 = models.CharField(max_length = 10)
    sporeCount48 = models.CharField(max_length = 10)
    sporeCount72 = models.CharField(max_length = 10)

    def __str__(self):
        return str(self.sampleID) + '-' + str(self.id)

sampling_event/forms.py
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django import forms

from django.conf import settings
from django.db import models
from models import SampleType


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']



class multiSample(forms.Form):
    samples = forms.IntegerField()
    #for type in SampleType.objects.all():

    #wipes = forms.IntegerField()
    #swabs = forms.IntegerField()
    #air = forms.IntegerField()
    #pos = forms.IntegerField(label="positive control")
    #neg = forms.IntegerField(label= "negative control")

sampling_event/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import sampleEvent, sample, plate
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView, BaseCreateView
from django.core.urlresolvers import reverse_lazy

from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm, multiSample


"""
class IndexView(generic.ListView):
    template_name = 'sampling_event/index.html'

    def get_queryset(self):
        return sampleEvent.objects.all()


class DetailView(generic.DetailView):
    model = sampleEvent
    template_name = 'sampling_event/detail.html'

"""


def index(request):
    all_sampleEvents = sampleEvent.objects.all()
    context = {'all_sampleEvents' : all_sampleEvents,}
    return render(request, 'sampling_event/index.html', context)


def detail(request, sampleEvent_id):
    sampleEven = get_object_or_404(sampleEvent, pk = sampleEvent_id)
    return render(request, 'sampling_event/detail.html', {'sampleEvent': sampleEven,})


class sampleEventCreate(CreateView):
    model = sampleEvent
    fields = ['date', 'assayName', 'coge', 'samplers', 'Site', 'facility', 'environment']

    def post(self, request, *args, **kwargs):
        self.object = None
        event = super(BaseCreateView, self).post(request, *args, **kwargs)


        return event


class sampleEventUpdate(UpdateView):
    model = sampleEvent
    fields = ['date', 'assayName', 'coge', 'samplers', 'Site', 'facility', 'environment']


class sampleEventDelete(DeleteView):
    model = sampleEvent
    success_url = reverse_lazy('sampling_event:index')


def sampleIndex(request, pk):
    sampleTemp = get_object_or_404(sample, pk=pk)
    return render(request, 'sampling_event/sample.html', {'sampleTemp': sampleTemp})


class sampleCreate(CreateView):
    model = sample
    fields = ['samplingEvent', 'sampleType', 'accountable', 'Zone', 'PooledID', 'serialNumber', 'description']


class sampleUpdate(UpdateView):
    model = sample
    fields = ['sampleType', 'sampleType', 'accountable', 'Zone', 'PooledID', 'serialNumber', 'description']


class sampleDelete(DeleteView):
    model = sample
    success_url = reverse_lazy('sampling_event:detail')




#class multiSampleCreate(View):
#    form_class = multiSample

"""
def multi_sample(request, sampleEvent_id):
    if request.method == "POST":
        form = multiSample(request.POST)
        if form.is_valid():
            #create a multiform sample page form and redirect to it
    else:
        form = multiSample()

    return render(request, )
"""





class UserFormView(View):
    form_class = UserForm
    template_name = 'sampling_event/registration_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned/ normalized data
            username= form.cleaned_data['username']
            password= form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns User objects if credientials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('sampling_event:index')

        return render(request, self.template_name, {'form': form})

sampling_event/templates/sampling_event/detail.html
<h2>Sampling Event Overview</h2>

<h2>{{sampleEvent.assayName}}</h2>
{{sampleEvent.date}} <br>

Coge: {{sampleEvent.coge}}  <br>
Samplers: {{sampleEvent.samplers}} <br>
Site: {{sampleEvent.Site}} <br>
Facility: {{sampleEvent.facility}} <br>
Environment: {{sampleEvent.environment}} <br>
Spacecraft: {{sampleEvent.spacecraft}} <br>


<h4> List of Samples</h4>


<u1>
    {% for sam in sampleEvent.sample_set.all %}
        <!--<li>{{sam}}</li> -->
        <a href="{% url 'sampling_event:sample-index' sam.id %}" class="btn btn-primary btn-sm" role="button"> {{ sam}} </a>


    {% endfor %}
    <br>
    <br>

     <!-- Update Sampling Event -->
    <form action="{% url 'sampling_event:sampleEvent-update' sampleEvent.id %}" method="post" style="display: inline;">
    </form>
    <form action="{% url 'sampling_event:sampleEvent-update' sampleEvent.id %}" method="post" style="display: inline;">
        {% csrf_token %}
        <input type="hidden" name="event_id" value="{{ sampleEvent.id }}"/>
        <button type="submit" class="btn btn-default btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp; Update Sampling Event
        </button>
    </form>
</u1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

sampling_event/templates/sampling_event/form_template.html
 {% for field in form %}
     <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
             <span class="text-danger small">{{ field.errors }}</span>
         </div>
         <label class="control-label col-sm-2">{{ field.label_tag }}</label>
         <div class="col-sm-10">{{ field }}</div>
     </div>
 {% endfor %}

sampling_event/templates/sampling_event/index.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.7/webcomponents-lite.min.js"></script>
<link rel="import" href="jpl-header.html">

 <!--
    <h3> Here are all the sampling events</h3>
    <ul>
        {% for event in all_sampleEvents %}
        <li><a href ="/sampling_event/{{event.id}}/">{{event.assayName}}</a></li>
        <a href="{% url 'sampling_event:detail' event.id %}"> {{event.assayName}}</a>

        {% endfor %}
    </ul>
    -->



 <div class="albums-container container-fluid">


     <!-- Sampling Events -->
     <h3> All Sampling Events</h3>
     <div class="row">
         <div class="col-sm-12">

         </div>

             {% for event in all_sampleEvents %}
                 <div class="col-sm-4 col-lg-2">






                             <!-- View Details -->
                             <a href="{% url 'sampling_event:detail' event.id %}" class="btn btn-primary btn-sm" role="button"> {{ event.assayName}} </a>


                             <!-- Delete Sampling Events-->
                             <form action="{% url 'sampling_event:sampleEvent-delete' event.id %}" method="post" style="display: inline;">
                                 {% csrf_token %}
                                 <input type="hidden" name="event_id" value="{{ event.id }}" />
                                 <button type="submit" class="btn btn-default btn-sm">
                                     <span class="glyphicon glyphicon-trash"></span>
                                 </button>
                             </form>




                         </div>
                     </div>
                 </div>
                 {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
             {% endfor %}

             <div class="col-sm-12">
                 <br>
                 <a href="{% url 'sampling_event:sampleEvent-add' %}">
                     <button type="button" class="btn btn-success">
                         <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Sampling Event
                     </button>
                 </a>
             </div>

     </div>
     </div>

sampling_event/templates/sampling_event/registration_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>

    <div class="container-fluid">

     <div class="row">


         <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                 <div class="panel-body">
                     <h3>Create New Account</h3>
                     {% if error_message %}
                         <p><strong>{{ error_message }}</strong></p>
                     {% endif %}
                     <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                         {% include 'sampling_event/form_template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>
                             </div>
                         </div>
                     </form>
                 </div>
             </div>
         </div>
    </div>
    </div>

sampling_event/templates/sampling_event/sample.html
<h2>Sample Overview</h2>

Sampling Event: {{sampleTemp.samplingEvent}}<br>
Sample Type: {{sampleTemp.sampleType}} <br>
Serial Number: {{sampleTemp.serialNumber}} <br>

sampling_event/templates/sampling_event/sampleEvent_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SampleEvent</title>

    <div class="container-fluid">

     <div class="row">


         <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                 <div class="panel-body">
                     <h3>Add a New Sampling Event</h3>
                     {% if error_message %}
                         <p><strong>{{ error_message }}</strong></p>
                     {% endif %}
                     <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                         {% include 'sampling_event/form_template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>
                             </div>
                         </div>
                     </form>
                 </div>
             </div>
         </div>
    </div>
    </div>

sampling_event/templates/sampling_event/sample_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sample</title>

    <div class="container-fluid">

     <div class="row">


         <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                 <div class="panel-body">
                     <h3>Add a New Sample</h3>
                     {% if error_message %}
                         <p><strong>{{ error_message }}</strong></p>
                     {% endif %}
                     <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                         {% include 'sampling_event/form_template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>
                             </div>
                         </div>
                     </form>
                 </div>
             </div>
         </div>
    </div>
    </div>